- name: Frontend App
  hosts: all
  become: yes

  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: Copy main nginx.conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expence.conf

    - name: Clean the old content
      ansible.builtin.file:
        src: /usr/share/nginx/html
        state: absent
    
    - name: Create App directory
      ansible.builtin.file:
        src: /usr/share/nginx/html
        state: directory

    - name: Download and Extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        destination: usr/share/nginx/html
        remote_src: yes

    - name: Ensure nginx is running
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes