- name: Frontend App
  hosts: all
  become: yes
  tasks:
    - name: Intall Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy Expense Nginx configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expence.conf

    - name: Clean the old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    
    - name: Create App directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and Extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Start Nginx Service
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes