  tasks:
    - name: Copy example.conf
      ansible.builtin.copy:
        src: example.conf
        dest: /tmp/example-copy.conf

    - name: Template example.conf
      ansible.builtin.template:
        src: example.conf
        dest: /tmp/example-template.conf